
data = [
    ("What foods are high in protein?", "nutrition"),
    ("Should I take multivitamins?", "nutrition"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("How often should I work out per week?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("Should I take multivitamins?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("How much fiber do I need daily?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("Should I take multivitamins?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("How much fiber do I need daily?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("Should I take multivitamins?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("How often should I work out per week?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How much fiber do I need daily?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("How often should I work out per week?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How much fiber do I need daily?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("Should I take multivitamins?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("How much fiber do I need daily?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("Should I take multivitamins?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("Should I take multivitamins?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("How do I get six-pack abs?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("What is a good post-workout routine?", "fitness"),
    ("What is the keto diet?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What is a balanced diet?", "nutrition"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("How can I increase my bench press?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("How often should I work out per week?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("How do I get six-pack abs?", "fitness"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("How can I increase my bench press?", "fitness"),
    ("What are the best sources of healthy fats?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What is a balanced diet?", "nutrition"),
    ("Are carbs bad for you?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("What are the benefits of stretching before a workout?", "fitness"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("Should I take multivitamins?", "nutrition"),
    ("What is the keto diet?", "nutrition"),
    ("What is a good warm-up routine?", "fitness"),
    ("How much fiber do I need daily?", "nutrition"),
    ("How do I improve my cardio endurance?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("Is weight training good for fat loss?", "fitness"),
    ("What is a good warm-up routine?", "fitness"),
    ("Are carbs bad for you?", "nutrition"),
    ("Is intermittent fasting effective for weight loss?", "nutrition"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What are the best exercises for building core strength?", "fitness"),
    ("What foods are high in protein?", "nutrition"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("How much fiber do I need daily?", "nutrition"),
    ("Should I take multivitamins?", "nutrition"),
    ("What foods are high in protein?", "nutrition"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("What is a good post-workout routine?", "fitness"),
    ("How can I gain muscle mass quickly?", "fitness"),
    ("What are the benefits of drinking green tea?", "nutrition"),
    ("How many calories should I eat daily to lose weight?", "nutrition"),
    ("Who discovered the theory of relativity?", "off_topic"),
    ("What is the tallest mountain in North America?", "off_topic"),
    ("Which country is known as the Land of the Midnight Sun?", "off_topic"),
    ("Who wrote the novel '1984'?", "off_topic"),
    ("What is the largest organ in the human body?", "off_topic"),
    ("Which planet is closest to the sun?", "off_topic"),
    ("Who was the first woman to win an Olympic gold medal?", "off_topic"),
    ("What is the capital city of Norway?", "off_topic"),
    ("Which element has the chemical symbol 'O'?", "off_topic"),
    ("Who painted the famous artwork 'The Scream'?", "off_topic"),
    ("What is the longest river in South America?", "off_topic"),
    ("Who was the first person to circumnavigate the globe?", "off_topic"),
    ("What is the capital of Portugal?", "off_topic"),
    ("Which country is home to the Great Wall?", "off_topic"),
    ("Who invented the first airplane?", "off_topic"),
    ("What is the currency of Egypt?", "off_topic"),
    ("Which city hosted the 2012 Summer Olympics?", "off_topic"),
    ("Who wrote 'The Catcher in the Rye'?", "off_topic"),
    ("What is the smallest continent by land area?", "off_topic"),
    ("Which gas do plants absorb from the atmosphere?", "off_topic"),
    ("Who was the first African-American president of the USA?", "off_topic"),
    ("What is the capital city of Indonesia?", "off_topic"),
    ("Which animal is known as the King of the Jungle?", "off_topic"),
    ("Who discovered penicillin?", "off_topic"),
    ("What is the largest desert in the world?", "off_topic"),
    ("Which ocean lies between Africa and Australia?", "off_topic"),
    ("Who painted the 'Mona Lisa'?", "off_topic"),
    ("What is the main ingredient in guacamole?", "off_topic"),
    ("Who was the first man to walk on the moon?", "off_topic"),
    ("What is the capital of Canada?", "off_topic"),
    ("Which country is famous for sushi?", "off_topic"),
    ("Who invented the telephone?", "off_topic"),
    ("What is the tallest building in the world?", "off_topic"),
    ("Which continent has the largest population?", "off_topic"),
    ("Who was the founder of Facebook?", "off_topic"),
    ("What is the capital of Argentina?", "off_topic"),
    ("Which country has the largest Muslim population?", "off_topic"),
    ("Who wrote 'Hamlet'?", "off_topic"),
    ("What is the boiling point of water in Celsius?", "off_topic"),
    ("Who was the first female Prime Minister of the UK?", "off_topic"),
    ("What is the capital city of South Korea?", "off_topic"),
    ("Which animal is the largest mammal on Earth?", "off_topic"),
    ("Who discovered gravity?", "off_topic"),
    ("What is the chemical symbol for gold?", "off_topic"),
    ("Which city is known as the Big Apple?", "off_topic"),
    ("Who painted 'Starry Night'?", "off_topic"),
    ("What is the name of the longest river in Africa?", "off_topic"),
    ("Who was the first emperor of Rome?", "off_topic"),
    ("Which country is famous for its tulips?", "off_topic"),
    ("What is the capital city of Turkey?", "off_topic"),
    ("Who was the first person in space?", "off_topic"),
    ("What is the name of the desert in northern Africa?", "off_topic"),
    ("Which country hosted the first FIFA World Cup?", "off_topic"),
    ("Who is the author of 'The Hobbit'?", "off_topic"),
    ("What is the chemical formula for water?", "off_topic"),
    ("Who was the first woman to fly solo across the Atlantic?", "off_topic"),
    ("What is the largest island in the Caribbean?", "off_topic"),
    ("Which country is known as the Land of the Rising Sun?", "off_topic"),
    ("Who discovered electricity?", "off_topic"),
    ("What is the capital city of Greece?", "off_topic"),
    ("Which planet is known as the Red Planet?", "off_topic"),
    ("Who painted the Sistine Chapel ceiling?", "off_topic"),
    ("What is the name of the largest volcano in the world?", "off_topic"),
    ("Who was the first person to summit Mount Everest?", "off_topic"),
    ("Which animal is known for its black and white stripes?", "off_topic"),
    ("What is the currency of Brazil?", "off_topic"),
    ("Who invented the printing press?", "off_topic"),
    ("What is the capital of New Zealand?", "off_topic"),
    ("Which continent is the Sahara Desert located in?", "off_topic"),
    ("Who was the first woman to win a Nobel Prize?", "off_topic"),
    ("What is the name of the famous bell in London?", "off_topic"),
    ("Who wrote 'Les Misérables'?", "off_topic"),
    ("What is the currency of Canada?", "off_topic"),
    ("Who was the first emperor of China?", "off_topic"),
    ("What is the largest stadium in the world?", "off_topic"),
    ("Which country is home to Machu Picchu?", "off_topic"),
    ("Who discovered America?", "off_topic"),
    ("What is the capital city of Thailand?", "off_topic"),
    ("Who invented the light bulb?", "off_topic"),
    ("Which country has the most pyramids?", "off_topic"),
    ("Who was the leader of the Soviet Union during WWII?", "off_topic"),
    ("What is the national animal of Australia?", "off_topic"),
    ("Who was the first woman to climb Mount Everest?", "off_topic"),
    ("What is the capital of the Philippines?", "off_topic"),
    ("Who founded the Roman Empire?", "off_topic"),
    ("Which city is known as the City of Love?", "off_topic"),
    ("Who invented the electric light bulb?", "off_topic"),
    ("What is the capital of Cuba?", "off_topic"),
    ("Who was the first president of South Africa?", "off_topic"),
    ("Which country invented paper?", "off_topic"),
    ("What is the largest bay in the USA?", "off_topic"),
    ("Who wrote 'Pride and Prejudice'?", "off_topic"),
    ("What is the currency of South Korea?", "off_topic"),
    ("Who was the first man to reach the South Pole?", "off_topic"),
    ("What is the capital of Malaysia?", "off_topic"),
    ("Who painted 'Girl with a Pearl Earring'?", "off_topic"),
    ("What is the name of the river running through Paris?", "off_topic"),
    ("Which continent has the most countries?", "off_topic"),
    ("Who wrote 'The Great Gatsby'?", "off_topic"),
    ("What is the tallest statue in the world?", "off_topic"),
    ("Who was the first president of the USA?", "off_topic"),
    ("Which country is famous for Oktoberfest?", "off_topic"),
    ("What is the currency of Russia?", "off_topic"),
    ("Who is the author of 'Harry Potter'?", "off_topic"),
    ("What is the largest desert in Asia?", "off_topic"),
    ("Who wrote 'The Odyssey'?", "off_topic"),
    ("What is the capital of Vietnam?", "off_topic"),
    ("Which country is known as the Land of Fire and Ice?", "off_topic"),
    ("What is the longest river in Asia?", "off_topic"),
    ("Who was the first person in space?", "off_topic"),
    ("What is the name of the famous amphitheater in Rome?", "off_topic"),
    ("Who was the first woman to win a Nobel Prize?", "off_topic"),
    ("What is the capital of Argentina?", "off_topic"),
    ("Which country is known for maple syrup?", "off_topic"),
    ("What is the largest lake in Africa?", "off_topic"),
    ("Who wrote 'To Kill a Mockingbird'?", "off_topic"),
    ("What is the capital city of Thailand?", "off_topic"),
    ("Who invented the light bulb?", "off_topic"),
    ("What is the name of the river that runs through Egypt?", "off_topic"),
    ("Which country has the most pyramids?", "off_topic"),
    ("What is the currency of South Africa?", "off_topic"),
    ("Who was the leader of the Soviet Union during WWII?", "off_topic"),
    ("What is the largest stadium in the world?", "off_topic"),
    ("Which country is home to the ancient city of Machu Picchu?", "off_topic"),
    ("Who painted the Sistine Chapel ceiling?", "off_topic"),
    ("What is the capital of New Zealand?", "off_topic"),
    ("Which country is known as the Land of the Rising Sun?", "off_topic"),
    ("What is the name of the largest volcano in the world?", "off_topic"),
    ("Who was the first female pilot to fly solo across the Atlantic?", "off_topic"),
    ("What is the largest rainforest in the world?", "off_topic"),
    ("Who wrote 'The Odyssey'?", "off_topic"),
    ("What is the currency of Brazil?", "off_topic"),
    ("Who invented the printing press?", "off_topic"),
    ("What is the capital of Kenya?", "off_topic"),
    ("Which country is famous for the Amazon Rainforest?", "off_topic"),
    ("Who painted 'American Gothic'?", "off_topic"),
    ("What is the name of the desert located in northern Africa?", "off_topic"),
    ("Who was the first person in space?", "off_topic"),
    ("What is the capital of Chile?", "off_topic"),
    ("Who wrote 'Les Misérables'?", "off_topic"),
    ("What is the currency of Canada?", "off_topic"),
    ("Who was the first emperor of China?", "off_topic"),
    ("What is the capital of Greece?", "off_topic"),
    ("Who discovered electricity?", "off_topic"),
    ("What is the name of the longest river in Asia?", "off_topic"),
    ("Who painted 'The Persistence of Memory'?", "off_topic"),
    ("What is the capital of Turkey?", "off_topic"),
    ("Who invented the computer?", "off_topic"),
    ("What is the largest city in India?", "off_topic"),
    ("Who was the first woman to climb Mount Everest?", "off_topic"),
    ("What is the name of the famous bell in London?", "off_topic"),
    ("What is the capital of the Philippines?", "off_topic"),
    ("Who was the founder of the Roman Empire?", "off_topic"),
    ("What is the largest city in Australia?", "off_topic"),
    ("Who invented the electric light bulb?", "off_topic"),
    ("What is the capital of Cuba?", "off_topic"),
    ("Who was the first president of South Africa?", "off_topic"),
    ("Which country invented paper?", "off_topic"),
    ("What is the name of the largest bay in the USA?", "off_topic"),
    ("Who wrote 'Pride and Prejudice'?", "off_topic"),
    ("What is the currency of South Korea?", "off_topic"),
    ("Who was the first man to reach the South Pole?", "off_topic"),
    ("What is the capital of Malaysia?", "off_topic"),
    ("Who painted the 'Girl with a Pearl Earring'?", "off_topic"),
    ("What is the name of the river that runs through Paris?", "off_topic"),
    ("Which continent has the most countries?", "off_topic"),
    ("Who is the author of 'The Great Gatsby'?", "off_topic"),
    ("What is the tallest statue in the world?", "off_topic"),
    ("Who was the first president of the USA?", "off_topic"),
    ("Which country is famous for the festival of Oktoberfest?", "off_topic"),
    ("What is the currency of Russia?", "off_topic"),
    ("Who is the author of 'The Hobbit'?", "off_topic"),
    ("What is the name of the largest desert in Asia?", "off_topic"),
    ("Who was the first woman to win a Nobel Prize?", "off_topic"),
    ("What is the largest stadium in the world?", "off_topic"),
    ("Who wrote 'The Iliad'?", "off_topic"),
    ("What is the capital of Vietnam?", "off_topic"),
    ("Which country is known as the Land of Fire and Ice?", "off_topic"),
    ("Who painted the Mona Lisa?", "off_topic"),
    ("What is the national animal of Australia?", "off_topic"),
    ("Where is the Taj Mahal located?", "off_topic"),
    ("What is the longest river in Africa?", "off_topic"),
    ("Who was the first man to walk on the moon?", "off_topic"),
    ("What is the currency used in Japan?", "off_topic"),
    ("Which city is known as the Big Apple?", "off_topic"),
    ("Who discovered America?", "off_topic"),
    ("What is the smallest country in the world?", "off_topic"),
    ("Who invented the telephone?", "off_topic"),
    ("What is the name of the longest mountain range in the world?", "off_topic"),
    ("Which ocean is the largest?", "off_topic"),
    ("Who wrote the play 'Hamlet'?", "off_topic"),
    ("What is the capital of Italy?", "off_topic"),
    ("Which country hosts the Oktoberfest?", "off_topic"),
    ("What is the name of the famous clock tower in London?", "off_topic"),
    ("Who was the first president of the United States?", "off_topic"),
    ("What is the largest island in the Mediterranean Sea?", "off_topic"),
    ("Who painted 'Starry Night'?", "off_topic"),
    ("What is the national sport of Brazil?", "off_topic"),
    ("Where is the Great Barrier Reef located?", "off_topic"),
    ("Who is the author of 'Harry Potter'?", "off_topic"),
    ("What is the capital of Russia?", "off_topic"),
    ("Which country is famous for tulips and windmills?", "off_topic"),
    ("What is the highest waterfall in the world?", "off_topic"),
    ("Who discovered penicillin?", "off_topic"),
    ("What is the currency of Mexico?", "off_topic"),
    ("Which continent is the Sahara Desert located in?", "off_topic"),
    ("What is the name of the famous amphitheater in Rome?", "off_topic"),
    ("What is the capital of Egypt?", "off_topic"),
    # ... (rest of the data)
]


GREETINGS = {
    "hi", "hello", "hey", "good morning", "good night", "nice", "thanks", "thank you",
    "morning", "night", "howdy", "hiya", "greetings", "welcome", "what's up", "yo",
    "sup", "cheers", "bonjour", "hola", "aloha", "salutations", "hiya", "hiya there",
    "good afternoon", "evening", "peace", "shalom", "namaste", "cya", "bye", "see ya",
    "take care", "goodbye", "later", "catch you later", "hiya friend", "how’s it going",
    "what's new", "long time no see", "hey there", "hi there", "how are you", "how are you doing",
    "all right", "bonjourno", "ciao", "ola", "g'day", "hiya mate", "top of the morning",
    "how goes it", "welcome back", "hey buddy", "hey pal", "hiya buddy", "peace out",
    "have a good day", "have a great day", "good to see you", "nice to see you",
    "pleased to meet you", "great to meet you", "yo yo", "hello there", "hiya there",
    "sup dude", "hiya dude", "hey man", "hey girl", "hey bro", "hey sis", "hiya bro",
    "hiya sis", "what's crackin", "whassup", "whatsup", "what’s happening", "howzit",
    "how’s life", "how’s things", "hiya matey", "hiya champ", "hiya pal", "hiya sunshine",
    "how’s tricks", "good tidings", "greetings and salutations", "hail", "well met",
    "how do you do", "yo there", "hiya stranger", "hey stranger", "cheerio", "aloha friend",
    "hiya pal", "ahoy", "howdy-do", "yoho", "hail fellow", "what's cracking",
    "how goes it", "greetings earthling", "peace be upon you", "guten tag",
    "guten morgen", "namaskar", "salve", "ciao bella", "saludos", "hello sunshine",
    "hey sunshine", "hiya sunshine", "greetings and felicitations", "bonjourno",
    "wassup", "how's tricks", "yo dude", "hey dude", "yo mate", "hey mate",
    "yo bro", "hey bro", "hiya buddy", "top of the day", "happy day",
    "good day mate", "allo", "aloha kakahiaka", "konnichiwa", "annyeong",
    "shalom aleichem", "assalamu alaikum", "namaskaram", "bonjour mes amis",
    "hiya champ", "hey champ", "hey there sport", "greetings friend",
    "how are things", "hiya matey", "howdy partner", "yo partner",
    "hello there mate", "hey there pal", "hey there champ", "good morrow",
    "greetings comrade", "salut", "peace and love", "hiya hero",
    "hey hero", "hello hero", "greetings mate", "yo sunshine", "hey sunshine",
    "howzit going", "hiya mate", "what's good", "hey there sunshine",
    "hiya mate", "what's happening", "hiya stranger", "hey stranger",
    "yo stranger", "hiya buddy ol' pal", "hiya amigo", "hola amigo",
    "hey amigo", "bonjourno", "yo yo yo", "sup homie", "hey homie",
    "yo homie", "hey yo", "yo yo", "hiya chief", "hey chief", "yo chief",
    "what's up man", "what's up buddy", "how's everything", "how's everything going",
    "how's life treating you", "how are you feeling", "how's your day", "hope you're well",
    "hope all is good", "hope all is well", "how's your week", "how's your morning",
    "how's your afternoon", "how's your evening", "howdy partner", "hey partner",
    "hey there partner", "hey friend", "hi friend", "hello friend", "hey buddy",
    "hi buddy", "hello buddy", "hi there buddy", "hey there buddy", "yo buddy",
    "what's cracking buddy", "greetings matey", "hello matey", "hi matey",
    "hiya matey", "good day matey", "how are you matey", "hiya champ",
    "hello champ", "hey champ", "how are you champ", "what's up champ",
    "hello sport", "hey sport", "hiya sport", "what's up sport", "how's it going sport",
    "good day sport", "hiya sunshine", "hello sunshine", "hey sunshine",
    "how are you sunshine", "what's up sunshine", "greetings sunshine",
    "hello there sunshine", "hiya sunshine", "hello stranger", "hey stranger",
    "hiya stranger", "what's up stranger", "greetings stranger", "good to see you stranger",
    "hello mate", "hi mate", "hey mate", "how are you mate", "what's up mate",
    "hiya mate", "greetings mate", "hello there mate", "how's it going mate",
    "howdy mate", "hey there mate", "hiya pal", "hello pal", "hey pal",
    "what's up pal", "greetings pal", "hi pal", "good day pal", "how are you pal",
    "hey there pal", "hello there pal", "hiya buddy ol' pal", "hello buddy ol' pal",
    "hey buddy ol' pal", "howdy buddy ol' pal", "yo buddy ol' pal",
    "how's tricks pal", "how's tricks mate", "what's cooking", "what's cooking good looking",
    "how's life mate", "how's life pal", "what's new pal", "what's new mate",
    "yo dude", "hey dude", "hi dude", "hello dude", "how are you dude",
    "what's up dude", "greetings dude", "what's happening dude", "yo homie",
    "hey homie", "hello homie", "hi homie", "how are you homie", "what's up homie",
    "greetings homie", "yo man", "hey man", "hello man", "hi man", "how are you man",
    "what's up man", "greetings man", "hey bro", "hi bro", "hello bro",
    "what's up bro", "greetings bro", "hey brother", "hi brother", "hello brother",
    "what's up brother", "greetings brother", "hey sis", "hi sis", "hello sis",
    "what's up sis", "greetings sis", "hey sister", "hi sister", "hello sister",
    "what's up sister", "greetings sister", "hiya champ", "howdy champ",
    "hello champ", "good morrow", "hail and well met", "top of the morning to you",
    "good day to you", "well met", "salutations friend", "salutations mate",
    "salutations pal", "salutations buddy", "joyous greetings", "warm greetings",
    "happy to see you", "delighted to meet you", "nice to meet you", "pleased to meet you",
    "how goes it", "how are things", "how are you doing today", "hope you're having a good day",
    "hope you're having a good one", "good to see you again", "long time no see",
    "nice to catch up", "how've you been", "what's new with you", "what's new today",
    "what's the latest", "anything new", "how's it hanging", "how's it going",
    "how's it rolling", "how's your day going", "what's happening", "what's good",
    "how are things going", "hope everything's fine", "hope you're doing well",
    "hope all is well with you", "hey there sunshine", "hello sunshine",
    "hiya sunshine", "good morning sunshine", "good evening sunshine",
    "hey there champ", "hello there champ", "hiya champ", "what's going on champ",
    "hey there sport", "hello there sport", "hiya sport", "what's going on sport",
    "yo yo yo", "yo yo", "yo yo yo yo", "yo yo yo homie", "sup homie",
    "sup dude", "sup man", "sup bro", "sup mate", "sup friend", "sup pal",
    "yo what’s good", "yo what's cracking", "yo what's popping", "yo what's shaking",
    "yo what's happening", "yo what's cooking", "yo what's going down",
    "yo what's up dog", "yo what's up dogg", "what's up dog", "what's up dogg",
    "how's it hanging", "how's it hanging man", "how's it hanging buddy",
    "how's it hanging mate", "what's good man", "what's good buddy", "what's good mate",
    "what's good bro", "what's good homie", "what's good dude", "greetings earthling",
    "hello earthling", "hey earthling", "hi earthling", "greetings traveler",
    "hello traveler", "hey traveler", "hi traveler", "welcome traveler",
    "welcome friend", "welcome mate", "welcome buddy", "welcome pal", "welcome home",
    "welcome back friend", "welcome back mate", "welcome back buddy",
    "welcome back pal", "welcome back home", "greetings and salutations",
    "warmest greetings", "best wishes", "sending greetings", "sending good vibes",
    "sending love", "sending peace", "peace and love", "peace out",
    "peace be with you", "may peace be upon you", "good tidings",
    "blessings to you", "blessings and peace", "namaste", "shalom",
    "assalamu alaikum", "hola amigo", "bonjour mon ami", "ciao bello",
    "aloha", "aloha kakahiaka", "konnichiwa", "annyeong", "sawubona",
    "good morning friend", "good evening friend", "good afternoon friend",
    "good night friend", "morning sunshine", "evening sunshine",
    "afternoon sunshine", "good day sunshine", "hiya sunshine",
    "hello sunshine", "hey sunshine", "good to see you", "nice to see you",
    "great to see you", "happy to see you", "glad to see you",
    "how've you been", "hope you're well", "hope you're good",
    "hope all is well", "hope you're having a good day", "hope you're having a great day",
    "hope everything is fine", "hope all is fine", "hope you're safe",
    "hope you're happy", "hope you're healthy", "hope you're doing fine",
    "how do you do", "how are things going", "how's life treating you",
    "how's everything", "how's everything going", "how's the family",
    "how's your family", "how's your work", "how's your job", "how's school",
    "how's college", "how's university", "how's everything at home",
    "how's everything at work", "how's everything at school", "how's the weather",
    "how's the weather treating you", "what's new with you", "anything new",
    "anything exciting", "anything fun", "what's the good word", "what's the buzz",
    "what's the scoop", "what's the story", "what's up with you",
    "what's going on", "what's going down", "what's popping", "what's cracking",
    "what's shaking", "what's cooking", "what's brewing", "what's happening",
    "what's the latest", "what's the news", "what's the update", "what's the plan",
    "what's the deal", "what's the damage", "what's the sitch", "what's the sitchuation",
    "how's tricks", "how goes it", "how goes the battle", "what's the good news",
    "what's the bad news", "what's the word on the street", "what's the vibe",
    "what's the scene", "how's the scene", "how's the vibe", "how's the groove",
    "how's the rhythm", "how's life", "how's life been treating you", "how's life treating you",
    "how's your spirit", "how's your soul", "how's your heart", "how's your mind",
    "how's your body", "how's your health", "how's your mood", "how's your energy",
    "how's your day been", "how's your week been", "how's your month been",
    "how's your year been", "how's your journey", "how's your adventure",
    "how's your quest", "how's your mission", "how's your project", "how's your work",
    "how's your studies", "how's your training", "how's your practice", "how's your game",
    "how's your hustle", "how's your grind", "how's your flow", "how's your vibe",
    "how's your mood today", "how's your energy today", "how's your focus today",
    "how's your drive today", "how's your spirit today", "how's your soul today",
    "how's your heart today", "how's your mind today", "how's your body today",
    "how are you feeling today", "how are you doing today", "how are you today",
    "how have you been", "how have you been lately", "how have you been doing",
    "how have you been feeling", "how are things with you", "how's life been",
    "how's life treating you lately", "how's the family doing", "how's everyone",
    "how's everyone doing", "how's everyone at home", "how's everyone at work",
    "how's everyone at school", "how's your day going so far", "how's your week going",
    "how's your month going", "how's your year going", "how's the weather there",
    "how's the weather where you are", "how's everything going with you",
    "how's everything been lately", "how's everything been going", "how are you holding up",
    "how are you getting on", "how are you coping", "how are you managing",
    "how are you doing these days", "how are things in your world", "how's your world",
    "what's new in your world", "what's new in your life", "what's good with you",
    "what's good in your life", "what's good in your world", "what's fresh",
    "what's fresh with you", "what's fresh in your life", "what's fresh in your world",
    "what's happening with you", "what's happening in your life", "what's happening in your world",
    "hey there sunshine", "hello sunshine", "hiya sunshine", "good morning sunshine",
    "good afternoon sunshine", "good evening sunshine", "good night sunshine",
    "hey there champ", "hello there champ", "hiya champ", "what's going on champ",
    "hey there sport", "hello there sport", "hiya sport", "what's going on sport",
    "hey there buddy", "hello there buddy", "hiya buddy", "what's going on buddy",
    "hey there friend", "hello there friend", "hiya friend", "what's going on friend",
    "hey there mate", "hello there mate", "hiya mate", "what's going on mate",
    "hey there pal", "hello there pal", "hiya pal", "what's going on pal",
    "hey there bro", "hello there bro", "hiya bro", "what's going on bro",
    "hey there dude", "hello there dude", "hiya dude", "what's going on dude",
    "hey there homie", "hello there homie", "hiya homie", "what's going on homie",
    "greetings and salutations", "good to see you", "nice to see you", "pleased to meet you",
    "happy to see you", "glad to see you", "nice catching up", "good catching up",
    "nice meeting you", "good meeting you", "pleased to meet you", "how do you do",
    "it's a pleasure", "it's a delight", "it's an honor", "how have you been",
    "long time no see", "been a while", "it's been a while", "what a surprise",
    "look who's here", "well, hello there", "hey stranger", "hello stranger",
    "hiya stranger", "greetings stranger", "good to see you stranger",
    "welcome back", "welcome home", "welcome aboard", "welcome to the team",
    "welcome to the club", "welcome to the party", "welcome friend", "welcome mate",
    "welcome buddy", "welcome pal", "welcome home", "glad you're here",
    "happy you're here", "nice to have you here", "pleased to have you here",
    "great to have you here", "welcome, glad you could make it",
    "hey hey", "hi hi", "hello hello", "howdy-doody", "hey sunshine!",
    "what's poppin'", "what's cookin' good lookin'", "yo what's crackin'",
    "how's it hanging?", "hey sugar", "hey there, good looking",
    "top of the morning", "good to see ya", "nice to see ya",
    "how’s your day been?", "hope you’re well today", "hope you’re feeling great",
    "long time, no chat", "nice running into you", "happy day to you",
    "greetings and good wishes", "good tidings to you",
    "pleased to cross paths", "what’s the buzz?", "what’s the word?",
    "hello, sunshine!", "hey buddy ol' pal", "how's the world treating you?",
    "good day to you, mate", "cheerio mate", "hiya sport!", "what’s the scoop?",
    "how’s tricks with you?", "good evening, friend", "how’s your spirit?",
    "happy to see you today", "how’s your journey?", "how’s the family doing?",
    "hope everything's peachy", "what’s new on your end?", "how’s everything rolling?",
    "hey, chief!", "hello, captain!", "how goes the battle?", "hiya, boss!",
    "what’s cracking, chief?", "hey there, champ!", "greetings, commander!",
    "how’s the hustle?", "hope your grind’s smooth", "what’s good, chief?",
    "hey pal, what’s happening?", "hiya, old friend", "hello, matey!",
    "top of the day to you", "blessings to you", "warm greetings!",
    "peace be with you", "what’s the haps?", "hey there, champ!",
    "hello there, legend!", "what’s cooking, ace?", "hiya, superstar!",
    "hey there, rockstar!", "how’s the vibe today?", "good to see you, chief!",
    "how’s the good fight?", "hope you’re shining bright", "hey, all-star!",
    "what’s shaking, bacon?", "yo, captain!", "good morning, sunshine!",
    "evening, pal!", "how’s the journey treating you?", "welcome aboard!",
    "glad you’re here", "happy you could join us", "hey there, comrade!",
    "hello, teammate!", "how’s the mission?", "how’s your day shaping up?",
    "good to catch up", "long time no see, friend", "hey, stranger!",
    "hope your day’s great", "hiya, legend!", "hello, mate!",
    "hi, boss!", "hey there, boss!", "how’s the kingdom?", "how’s your day so far?",
    "hope you’re having a blast", "what’s new and exciting?", "how’s your world?",
    "hey, partner!", "hello, sidekick!", "howdy, deputy!",
    "what’s the good word?", "greetings, old sport!", "how’s your week going?",
    "hope you’re keeping well", "hiya, mate!", "good to see you again!",
    "hello, dear friend!", "hiya, dear!", "hey there, pal!",
    "how’s everything in your world?", "what’s the plan today?", "how’s the weather treating you?",
    "hope all is swell", "how’s your energy today?", "what’s the vibe like?",
    "hey there, pal-o-mine!", "hello there, amigo!", "greetings, compadre!",
    "how’s the fiesta?", "what’s happening, dude?", "hope you’re doing swell!",
    "hello, sunshine!", "hey, star!", "good day, champ!", "top of the day, mate!",
    "good morning, chief!", "howdy, partner!", "greetings, traveler!",
    "hello, explorer!", "how’s the adventure?", "hope you’re well and happy!",
    "hey, sport!", "hello, captain!", "what’s up, skipper?", "greetings, mate!",
    "how’s the hustle treating you?", "hope you’re having a good one!",
    "hiya, superstar!", "good to see you shining!", "hey there, champ!",
    "hello, tiger!", "how’s the day treating you?", "what’s the latest, mate?",
    "hope your day’s full of smiles", "hello, bright one!", "hey, shining star!",
    "greetings and good vibes", "hope your spirit’s high", "hello, my friend!",
    "hiya, buddy!", "what’s cooking, good looking?", "hey there, ace!",
    "how’s life treating you today?", "greetings from afar!", "hope to see you soon!",
    "what’s the good news today?", "hello, beautiful!", "hey, handsome!",
    "hope your day is awesome!", "hiya, friend!", "hello, buddy!",
    "hey there, pal!", "what’s cracking, friend?", "hope everything’s great!",
    "greetings and salutations!", "how’s the day going?", "hey, rockstar!",
    "hello, legend!", "hope you’re feeling fantastic!", "what’s the good word?",
    "how’s your heart today?", "hope your soul’s smiling!", "good vibes your way!",
    "hey, friend-o!", "hello, bestie!", "greetings, mate!",
    "hope your week’s fantastic!", "hello, old friend!", "how’s your journey today?",
    "what’s happening in your world?", "good to see you, champ!", "hope you’re thriving!",
    "hey there, buddy!", "hello, comrade!", "hope your day is wonderful!",
    "greetings and hugs!", "hey there, sunshine!", "good morning, star!",
    "how’s your mood today?", "hope you’re feeling great!", "what’s the buzz, mate?",
    "hello, my pal!", "hey there, matey!", "hope your day’s going great!",
    "how’s your spirit?", "what’s new in your world?", "hope all is swell with you!",
    "hey, bright light!", "hello, spark!", "hope your day is bright!",
    "what’s good, friend?", "hope your day is amazing!", "hello, sunshine!",
    "hey, love!", "hope your heart is happy!", "good day to you, friend!",
    "how’s the world treating you?", "hope you’re well and happy!", "hey, old sport!",
    "hello, my dear!", "hope your soul is light!", "good to see you, mate!",
    "what’s new and exciting?", "hope your day’s fantastic!", "hello, bright star!",
    "hey, champ!", "how’s your energy today?", "hope your day is full of joy!",
    "hello, good looking!", "hey, pal!", "hope your week is fantastic!",
    "what’s new today?", "hope you’re having a good one!", "hello, friend!",
    "hey, buddy!", "hope your day’s great!", "good to see you, champ!",
    "hope you’re having a great day!", "what’s the good news?", "hello, mate!",
    "hey there, friend!", "hope all is well!", "good day, friend!",
    "how’s your day going?", "hope you’re doing well today!", "hello, sunshine!",
    "hey there, star!", "hope your day is amazing!", "what’s new, friend?",
    "hello, buddy ol’ pal!", "hey, matey!", "hope you’re feeling fantastic!",
    "how’s your day shaping up?", "hope you’re having fun today!", "hello, champ!",
    "hey there, pal!", "hope you’re keeping well!", "good to see you today!",
    "hope your day’s full of smiles!", "hello, bright one!", "hey, shining star!",
    "hope you’re having an awesome day!", "what’s the latest?", "hello, friend!",
    "hey there, buddy!", "hope all is well with you!", "good to see you, mate!",
    "hope you’re feeling great today!", "hello, sunshine!", "hey, star!",
    "hope your day is wonderful!", "what’s new with you?", "hello, buddy!",
    "hey there, friend!", "hope your day’s fantastic!", "good to see you today!",
    "hope you’re doing well!", "hello, champ!", "hey there, pal!",
    "hope your day is amazing!", "what’s happening?", "hello, buddy!",
    "hey, mate!", "hope you’re having a great day!", "good to see you, friend!",
    "hope you’re feeling fantastic!", "hello, sunshine!", "hey, star!",
    "hope your day is bright and full of joy!", "what’s new today?",
    "hello, friend!", "hey there, buddy!", "hope all is well with you!",
    "good to see you, mate!", "hope you’re feeling great today!", "hello, champ!",
        "aloha", "bonjour", "hola amigo", "ciao bella", "namaste",
    "shalom", "guten tag", "salutations", "hey there, sunshine!",
    "hiya pal", "hello stranger", "what’s good?", "hey hey hey",
    "hiya buddy", "g’day mate", "hello hello hello", "hi friend",
    "hey chief", "how’s it going today?", "hello friend-o",
    "hey sunshine pie", "greetings friend", "hiya buddy ol’ pal",
    "hello there, sport", "hey buddy bear", "hi there, chief",
    "greetings, comrade", "hello, matey", "hey captain",
    "what’s up buttercup?", "hello sunshine face", "hiya superstar",
    "hey champ", "how are you today?", "hi friend-o-mine",
    "good day sunshine", "greetings and salutations", "hello my friend",
    "hey partner in crime", "hi pal", "hello sunshine smile",
    "what’s the story?", "hey there, friend", "hiya boss",
    "hello there, tiger", "hey bud", "hi sunshine",
    "greetings and hugs", "hello there, hero", "hey bright eyes",
    "hi buddy boy", "hello sunshine soul", "hey there buddy bear",
    "howdy partner", "greetings pal", "hello sunshine ray",
    "hey there, mate", "hi sunshine face", "hello bright one",
    "what’s cooking?", "hey sunshine child", "hi there champ",
    "hello starshine", "hey there, buddy ol’ pal", "greetings sunshine",
    "hi bright star", "hello my buddy", "hey there, captain",
    "how’s life?", "hello sunshine buddy", "hi there sport",
    "hey bright spark", "greetings my friend", "hello sunshine face",
    "what’s new?", "hey there chief", "hi buddy boy",
    "hello friend-o", "hey sunshine soul", "hi there buddy bear",
    "good morning champ", "hello sunshine ray", "hey there, hero",
    "hi bright eyes", "greetings pal", "hello sunshine face",
    "hey there, mate", "hi sunshine soul", "hello bright one",
    "what’s happening?", "hey sunshine child", "hi there champ",
    "hello starshine", "hey buddy ol’ pal", "greetings sunshine",
    "hi bright star", "hello my buddy", "hey captain",
    "how’s it going?", "hello sunshine buddy", "hi there sport",
    "hey bright spark", "greetings my friend", "hello sunshine face",
    "what’s the deal?", "hey there chief", "hi buddy boy",
    "hello friend-o", "hey sunshine soul", "hi there buddy bear",
    "good evening champ", "hello sunshine ray", "hey there, hero",
    "hi bright eyes", "greetings pal", "hello sunshine face",
    "hey there, mate", "hi sunshine soul", "hello bright one",
    "what’s new today?", "hey sunshine child", "hi there champ",
    "hello starshine", "hey buddy ol’ pal", "greetings sunshine",
    "hi bright star", "hello my buddy", "hey captain",
    "how’s your day?", "hello sunshine buddy", "hi there sport",
    "hey bright spark", "greetings my friend", "hello sunshine face",
    "what’s going on?", "hey there chief", "hi buddy boy",
    "hello friend-o", "hey sunshine soul", "hi there buddy bear",
    "good to see you champ", "hello sunshine ray", "hey there, hero",
    "hi bright eyes", "greetings pal", "hello sunshine face",
    "hey there, mate", "hi sunshine soul", "hello bright one",
    "what’s the news?", "hey sunshine child", "hi there champ",
    "hello starshine", "hey buddy ol’ pal", "greetings sunshine",
    "hi bright star", "hello my buddy", "hey captain",
    "how have you been?", "hello sunshine buddy", "hi there sport",
    "hey bright spark", "greetings my friend", "hello sunshine face",
    "what’s the word?", "hey there chief", "hi buddy boy",
    "hello friend-o", "hey sunshine soul", "hi there buddy bear",
    "good to see you friend", "hello sunshine ray", "hey there, hero",
    "hi bright eyes", "greetings pal", "hello sunshine face",
    "hey there, mate", "hi sunshine soul", "hello bright one",
    "what’s up today?", "hey sunshine child", "hi there champ",
    "hello starshine", "hey buddy ol’ pal", "greetings sunshine",
    "hi bright star", "hello my buddy", "hey captain",
    "how’s everything?", "hello sunshine buddy", "hi there sport",
    "hey bright spark", "greetings my friend", "hello sunshine face",
    "what’s cracking?", "hey there chief", "hi buddy boy",
    "hello friend-o", "hey sunshine soul", "hi there buddy bear",
    "good to see you buddy", "hello sunshine ray", "hey there, hero",
    "hi bright eyes", "greetings pal", "hello sunshine face",
    "hey there, mate", "hi sunshine soul", "hello bright one",
    "what’s shaking?", "hey sunshine child", "hi there champ",
    "hello starshine", "hey buddy ol’ pal", "greetings sunshine",
    "hi bright star", "hello my buddy", "hey captain",
    "how are things?", "hello sunshine buddy", "hi there sport",
    "hey bright spark", "greetings my friend", "hello sunshine face",
    "what’s the scoop?", "hey there chief", "hi buddy boy",
    "hello friend-o", "hey sunshine soul", "hi there buddy bear",
    "good day mate", "hello sunshine ray", "hey there, hero",
    "hi bright eyes", "greetings pal", "hello sunshine face",
    "hey there, mate", "hi sunshine soul", "hello bright one",
    "what’s going?", "hey sunshine child", "hi there champ",
    "hello starshine", "hey buddy ol’ pal", "greetings sunshine",
    "hi bright star", "hello my buddy", "hey captain",
    "how’s the vibe?", "hello sunshine buddy", "hi there sport",
    "hey bright spark", "greetings my friend", "hello sunshine face",
    "what’s the situation?", "hey there chief", "hi buddy boy",
    "hello friend-o", "hey sunshine soul", "hi there buddy bear",
    "good to see you pal", "hello sunshine ray", "hey there, hero",
    "hi bright eyes", "greetings pal", "hello sunshine face",
    "hey there, mate", "hi sunshine soul", "hello bright one",
    "what’s the haps?", "hey sunshine child", "hi there champ",
    "hello starshine", "hey buddy ol’ pal", "greetings sunshine",
    "hi bright star", "hello my buddy", "hey captain",
    "how’s life treating you?", "hello sunshine buddy", "hi there sport",
    "hey bright spark", "greetings my friend", "hello sunshine face"
}




# List of offensive words
OFFENSIVE_WORDS = {
    "fuck", "shit", "bitch", "asshole", "damn", "crap", "bastard", "dick", "piss",
    "douche", "slut", "whore", "bollocks", "bugger", "twat", "prick", "cunt", "arsehole",
    "jerk", "motherfucker", "shithead", "dumbass", "dickhead", "moron", "idiot", "fag",
    "retard", "nigger", "chink", "spic", "kike", "dyke", "tranny", "gook", "coon",
    "wanker", "tosser", "git", "twit", "numbnuts", "jackass", "knobhead", "pissant",
    "shitbag", "shitface", "dickwad", "dickweed", "douchebag", "twatwaffle", "asshat",
    "asswipe", "buttface", "clown", "cretin", "cuck", "cumdumpster", "fuckface",
    "fuckstick", "motherfucking", "shitstain", "shitcunt", "shitdick", "twatwaffle",
    "dipshit", "dumbfuck", "dumbshit", "faggot", "fucknut", "fucktard", "gobshite",
    "jackwagon", "knob", "knobend", "muppet", "prat", "plonker", "tosspot", "wazzock",
    "wanker", "twunt", "twat", "twathead", "wank", "shitforbrains", "shitheel",
    "shitfucker", "assclown", "arsewipe", "bollockhead", "gobshite", "minger", "slag",
    "slagbag", "tosser", "bitchass", "bitchtits", "cocksucker", "cockwomble", "cumguzzler",
    "fuckface", "fucknugget", "fuckwit", "gash", "gashbag", "gobshite", "muffdiver",
        "arse", "bollocks", "bugger", "bloody", "cock", "cunt", "dick", "douche", "fag", "faggot",
    "git", "prick", "piss", "pissed", "twat", "wanker", "slut", "jerk", "knob", "knobhead",
    "tosser", "minger", "pillock", "munter", "bastard", "bollocks", "arsehole", "bellend",
    "clunge", "chode", "wazzock", "git", "muppet", "scrote", "slag", "shag", "tosspot",
    "twat", "berk", "plonker", "numpty", "pillock", "prat", "div", "douchebag", "twat",
    "nobhead", "slag", "berk", "fanny", "bugger", "prick", "wank", "twit", "trollop",
    "wazzock", "muppet", "plonker", "tosser", "daft cunt", "dickhead", "cocksucker",
    "shithead", "knobhead", "arsewipe", "bollockhead", "dickweed", "shitbag", "pisshead",
    "fuckwit", "tosspot", "arsewipe", "numbnuts", "dicknose", "shitstain", "fuckstick",
    "twatwaffle", "cumdumpster", "cocksplat", "shitforbrains", "dickface", "asshat",
    "fuckface", "cockwomble", "cockmuncher", "dickhead", "shitbag", "arseclown", "fucknut",
    "bellend", "twatface", "shitgibbon", "cuntwaffle", "prickface", "dicklicker",
    "cockknocker", "asswipe", "shitlicker", "fucknugget", "twatwaffle", "assclown",
    "cockwomble", "dickweed", "pissflaps", "bollocks", "arsehat", "shitheel", "twat",
    "maggot", "wazzock", "cumguzzler", "prickhead", "shitbreath", "cockbreath",
    "arsebreath", "dickbreath", "cuntbreath", "shitlicker", "dickhead", "asshat",
    "fuckwit", "dickwad", "cockwomble", "arsehole", "prick", "twatwaffle", "shitbag",
    "bollocks", "pisshead", "cocknose", "shithead", "wankstain", "fucktard",
    "dickhead", "assclown", "shitstain", "twatwaffle", "cockmonger", "pissflap",
    "arseface", "dicknose", "fuckbucket", "shitface", "twatwaffle", "cockbite",
    "asswipe", "dickweasel", "fucknugget", "pissflaps", "shitlicker", "cockknob",
    "arsehat", "twatlicker", "dickweed", "fuckwit", "pissflap", "shithead",
    "cockwomble", "arsehole", "twatwaffle", "dickface", "fuckstick", "pissflaps",
    "shitstain", "cockmuncher", "arsewipe", "twatface", "dickhead", "fucknut",
    "pissface", "shitbag", "cockbreath", "arsehat", "twatwaffle", "dickwad",
    "fucktard", "pissflap", "shitheel", "cocknose", "arsehole", "twatwaffle",
    "dickweed", "fuckwit", "pisshead", "shitface", "cockwomble", "arseclown",
    "twatwaffle", "dicklicker", "fuckstick", "pissflaps", "shitstain", "cockmonger",
    "arsewipe", "twatface", "dickhead", "fucknut", "pissface", "shitbag",
    "cockbreath", "arsehat", "twatwaffle", "dickwad", "fucktard", "pissflap",
    "shitheel", "cocknose", "arsehole", "twatwaffle", "dickweed", "fuckwit",
    "pisshead", "shitface", "cockwomble", "arseclown", "twatwaffle", "dicklicker",
    "fuckstick", "pissflaps", "shitstain", "cockmonger", "arsewipe", "twatface",
    "dickhead", "fucknut", "pissface", "shitbag", "cockbreath", "arsehat",
    "twatwaffle", "dickwad", "fucktard", "pissflap", "shitheel", "cocknose",
    "arsehole", "twatwaffle", "dickweed", "fuckwit", "pisshead", "shitface",
    "cockwomble", "arseclown", "twatwaffle", "dicklicker", "fuckstick", "pissflaps",
    "shitstain", "cockmonger", "arsewipe", "twatface", "dickhead", "fucknut",
    "pissface", "shitbag", "cockbreath", "arsehat", "twatwaffle", "dickwad",
    "fucktard", "pissflap", "shitheel", "cocknose", "arsehole", "twatwaffle",
    "arsebandit", "arsebreath", "arsecrack", "arseface", "arsefucker", "arsegoblin", 
    "arseholeface", "arseholelicker", "arsekisser", "arselicker", "arsemonkey", 
    "arsemunch", "arsemuncher", "arseplank", "arsepocket", "arsesnot", "arsespunk", 
    "arsestain", "assbag", "assbandit", "assbite", "assclown", "asscock", "asscracker", 
    "asscrumb", "asscunt", "assdouche", "assface", "assfucker", "assgoblin", "asshat", 
    "assholeface", "assholer", "assholery", "asshopper", "assjuice", "asslick", 
    "asslicker", "assmonkey", "assmunch", "assmuncher", "assnugget", "asspirate", 
    "asspocket", "asspuppet", "asspuss", "asspuppy", "assrat", "assshit", "assshole", 
    "asssucker", "asswad", "asswipe", "asswipes", "azzhole", "ballbag", "ballbust", 
    "ballbuster", "balllicker", "ballsack", "ballsucker", "batshit", "beastiality", 
    "bellend", "bitchass", "bitchtits", "blowjob", "bollocks", "bollox", "boner", 
    "boob", "boobs", "booby", "booger", "bugger", "bullshit", "bumfuck", "butt", 
    "buttbang", "buttfuck", "buttlicker", "buttmunch", "buttpirate", "buttplug", 
    "clit", "clitface", "clitfuck", "clusterfuck", "cockbite", "cockburger", 
    "cockface", "cockfucker", "cockhead", "cockknocker", "cocklicker", "cockmaster", 
    "cockmongler", "cockmuncher", "cocknose", "cocknugget", "cockqueen", "cockrider", 
    "cocksplat", "cockstain", "cockwaffle", "coon", "coonass", "cuntlicker", "cunts", 
    "cuntwaffle", "dickbrain", "dickbreath", "dickface", "dickfuck", "dickhead", 
    "dickhole", "dickjuice", "dicklicker", "dickmilk", "dicknose", "dickripper", 
    "dicksucker", "dickweed", "dickwod", "dike", "dildo", "dingleberry", "dipshit", 
    "douchebag", "douchecanoe", "douchewaffle", "dumbass", "dumbfuck", "dumbshit", 
    "dyke", "fagfucker", "faggot", "fartknocker", "fatass", "fatfuck", "fatshit", 
    "fuckface", "fuckhead", "fucknut", "fuckstick", "fucktard", "fudgepacker", 
    "futanari", "gook", "gooch", "goochbag", "gook", "handjob", "hardon", "hellfuck", 
    "hellshit", "homo", "hooker", "jackass", "jackoff", "jap", "jerkoff", "jizz", 
    "kike", "klootzak", "knob", "knobend", "knobhead", "kunt", "kyke", "lesbo", 
    "lezzie", "mcfagget", "minge", "mong", "mothafucka", "motherfucker", "motherfucking", 
    "muff", "munging", "nigga", "nigger", "niglet", "numbnuts", "nutsack", "paki", 
    "panooch", "peckerhead", "penisfucker", "phuck", "pissflaps", "pissed", "pissedoff", 
    "pissflap", "polesmoker", "poon", "poonani", "poonany", "poontang", "prickhead", 
    "punani", "pussylicker", "pussylicking", "pussypounder", "queef", "queer", "rimjob", 
    "schizo", "scrote", "shitass", "shitbag", "shitbrains", "shitbreath", "shitcunt", 
    "shitdick", "shitface", "shitfaced", "shithead", "shitlist", "shitskin", "shitter", 
    "shittiest", "shitting", "shitty", "skank", "skankbag", "slutbag", "slutface", 
    "slutfuck", "slutty", "smeg", "snatch", "spic", "spick", "spik", "spook", "splooge", 
    "spunk", "spunky", "tard", "tittyfuck", "tittywank", "tosser", "twatwaffle", 
    "twatface", "twatlicker", "twats", "uncle tom", "vajayjay", "vag", "vaginawarts", 
    "vjayjay", "wanker", "wetback", "whorebag", "whoreface", "whorefuck", "whorehouse", 
    "wop", "wrasslin", "yaoi", "yid", "zipperhead", "zits", 
    "abused", "acidhead", "aggro", "airhead", "anus", "apeshit", "arsehole", "assbagger", 
    "assbandit", "assbite", "assclown", "asscock", "asscracker", "asscrumb", "asscunt", 
    "assdick", "assface", "assfuck", "assfucker", "assgoblin", "asshat", "asshead", 
    "asshole", "assholery", "asshopper", "assjacker", "asskiss", "asskisser", "asslicker", 
    "assmonkey", "assmunch", "assmuncher", "assnugget", "asspacker", "asspirate", 
    "asspocket", "asspunch", "assrabbit", "assranger", "assrat", "assshit", "assshole", 
    "asssucker", "asswad", "asswipe", "azz", "azzhole", "ballbag", "balllicker", 
    "ballwasher", "batshit", "beastiality", "bitchass", "bitchtits", "blowjob", "bollocks", 
    "bollocksy", "bollox", "boner", "boob", "boobs", "booby", "booger", "bugger", "bullshit", 
    "bumfuck", "buttfucka", "butthole", "buttmuncher", "buttpirate", "buttplug", "cack", 
    "cameltoe", "carpetmuncher", "chesticle", "chink", "choad", "chode", "chug", "clit", 
    "clitface", "clitorous", "clusterfuck", "cockbite", "cockburger", "cockface", "cockfucker", 
    "cockhead", "cockknocker", "cocklicker", "cockmaster", "cockmongler", "cockmuncher", 
    "cocknose", "cocknugget", "cockqueen", "cockrider", "cocksplat", "cockstain", "cockwaffle", 
    "cooch", "coochie", "coonass", "cornhole", "cumdumpster", "cumguzzler", "cumjockey", 
    "cumslut", "cumsucker", "cuntlicker", "cuntrag", "cuntwaffle", "dickbag", "dickbrain", 
    "dickbreath", "dickface", "dickfuck", "dickhead", "dickhole", "dickjuice", "dicklicker", 
    "dickmilk", "dicknose", "dickripper", "dicksucker", "dickweed", "dickwod", "dike", 
    "dildo", "dingleberry", "dipshit", "douchecanoe", "douchelord", "douchenozzle", "douchewaffle", 
    "dumbass", "dumbfuck", "dumbshit", "dyke", "fagfucker", "faggot", "fartknocker", "fatass", 
    "fatfuck", "fatshit", "fuckass", "fuckbag", "fuckboy", "fuckbrain", "fuckbucket", "fuckface", 
    "fuckhead", "fucknut", "fuckstick", "fucktard", "fudgepacker", "gash", "gashbag", "gashface", 
    "goddamn", "gooch", "goochbag", "gook", "handjob", "hardon", "hellbent", "hellfuck", "hellshit", 
    "homo", "hooker", "jackass", "jackoff", "jerkoff", "jizz", "jizzmopper", "kike", "klootzak", 
    "knob", "knobend", "knobhead", "kunt", "kyke", "lesbo", "lezzie", "mcfagget", "minge", "mong", 
    "mothafucka", "motherfucker", "motherfucking", "muffdiver", "munging", "nigga", "nigger", 
    "niglet", "numpty", "numbnuts", "nutsack", "paki", "panooch", "pecker", "peckerhead", "penisfucker", 
    "phuck", "pissflaps", "pissed", "pissedoff", "pissflap", "polesmoker", "poon", "poonani", 
    "poonany", "poontang", "prickhead", "punani", "pussylicker", "pussylicking", "pussypounder", 
    "queef", "queer", "rimjob", "schizo", "scrote", "shitass", "shitbag", "shitbrains", "shitbreath", 
    "shitcunt", "shitdick", "shitface", "shitfaced", "shithead", "shitlist", "shitskin", "shitter", 
    "shittiest", "shitting", "shitty", "skank", "skankbag", "slutbag", "slutface", "slutfuck", 
    "slutty", "smeg", "snatch", "spic", "spick", "spik", "spook", "splooge", "spunk", "spunky", 
    "tard", "tittyfuck", "tittywank", "tosser", "twatwaffle", "twatface", "twatlicker", "twats", 
    "uncle tom", "vajayjay", "vag", "vaginawarts", "vjayjay", "wank", "wanker", "wetback", 
    "whorebag", "whoreface", "whorefuck", "whorehouse", "wop", "wrasslin", "yaoi", "yid", "zipperhead"
}
